# Generated by Django 5.0.14 on 2026-02-21 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('whatsapp', models.CharField(help_text='Format : +22967xxxxxx ou numéro international', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Numéro invalide. Utilisez le format international, ex : +22967000000 ou +33612345678', regex='^\\+?[0-9]{8,15}$')], verbose_name='Numéro WhatsApp')),
                ('etablissement', models.CharField(blank=True, default='', help_text='Ex : ENSET – Génie Électrique', max_length=200, verbose_name='Établissement / Filière')),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numéro de ticket')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['-created_at'],
            },
        ),
    ]
